// export Signup from './Signup/Signup';
export About from './About/About';
export Address from './Address/Address';
export Contacts from './Contacts/Contacts';
export Home from './Home/Home';
export Main from './Main/Main';
export Maps from './Maps/Maps';
export Test from './Test/Test';
export EventsList from './Events/EventsList';
export EventDetails from './Event/EventDetails';
export Guest from './Guest/sampleGuest';
export Gift from './Gift/sampleGift';
